#!/usr/bin/perl

# After invoking mdga2inv.pl we are left with a series of .inv files that hold the Zernike Descriptors
# for docking predictions generated by Multi-LZerD. We have the ZD's that correspond to both the PDB predictions
# and the simulated EM structures of them.
# We want to see if the distance between the EM-3DZD's is useful for structure comparison purposes.
# We can do that by comparing them to PDB-3DZD distances, which we already know are useful, and also against the
# actual RMSD between the native complex and the predictions
#
# This script generates a file with 3 columns:
# 1. distance between each PDB-decoy and the native (calculated by suing the invdistance.pl program)
# 2. distance between each EM-decoy and the simulated EM-native (invdistance.pl)
# 3. RMSD between PDB decoy and PDB native (extracted from a previously generated Multi-LZerD stats file)
#
# These values allow us to generate correlation plots/values for analysis

if($#ARGV + 1 != 5)
{
	# start and end just determine the first index and the last index of the files to be processed
	print "Usage: emstats.pl <PDBID> <inv files directory> <start> <end> <Multi-LZerD stats file>\n";
}
else
{
	$pdbid = $ARGV[0];
	$directory = $ARGV[1];
	$start = $ARGV[2];
	$end = $ARGV[3];
	$statsfile = $ARGV[4];

	# create variables that hold the filename of the native inv files
	$nativepdbinv = "$directory/$pdbid.pdb.inv";
	$nativeeminv = "$directory/$pdbid.em.inv";

	# read the rmsd values from the stats file
	@rmsdvalues = `filterrmsd.pl $statsfile`;
	chomp(@rmsdvalues);

	while($start <= $end)
	{
		$filenumber = sprintf("%05d", $start);
		$pdbinv = "$directory/$pdbid-$filenumber.pdb.inv";
		$eminv = "$directory/$pdbid-$filenumber.em.inv";

		$pdbdistance = `invdistance.pl $nativepdbinv $pdbinv`;
		$emdistance = `invdistance.pl $nativeeminv $eminv`;

		chomp($pdbdistance);
		chomp($emdistance);

		$rmsd = $rmsdvalues[$start - 1]; # -1 because file names start from 1 while the rmsd values are read from a 0 indexed array

		print("$start,$pdbdistance,$emdistance,$rmsd\n");

		$start++;
	}
}
