#!/bin/sh

# Takes a .ga.out file generated by the multiple docking program and extracts only the values
# corresponding to the final score, and each of the terms used in the linear combination to generate the final score

if test $# -ne 1; then
awk -F"," '{for(i=NF-12; i <= NF; i++) printf "%11s ",$i; printf "\n"}'
#echo Usage: filterscores.sh scoresfile ;
#exit 0
fi

awk -F"," '{for(i=NF-12; i <= NF; i++) printf "%11s ",$i; printf "\n"}' $1
