#!/usr/bin/perl

# Takes a .ga.out file generated by the multiple docking program and extracts only the values
# in the "RMSD" column

if($#ARGV + 1 == 1)
{
	# if a parameter is provided then it's assumed that it's a file that can be used as source
	open(STATSFILE, $ARGV[0]);
	@lines = <STATSFILE>;
	close(STATSFILE);
}
else
{
	#by default we assume that the input is th stdinput
	@lines = <STDIN>;
}
chomp(@lines);

#the first line corresponds to the headers
@headers = split(/,/, $lines[0]);
#search for "RMSD" which is the title of the column we're looking for
for($columnindex = 0; $columnindex < $#headers + 1; $columnindex++)
{
	if($headers[$columnindex] eq "RMSD")
	{
		last;
	}
}

#at this point column index holds the column number that corresponds to each RMSD value

for($row = 1; $row < $#lines + 1; $row++)
{
	@values = split(/,/, $lines[$row]);
	$rmsdvalue = $values[$columnindex];
	print "$rmsdvalue\n";
}
